name: opentodolist
version: 3.16.1
confinement: strict
grade: stable
base: core18
adopt-info: opentodolist # part to adopt appstream data from (first in parse list)
apps:
    opentodolist:
        command: kf5-launch OpenTodoList
        plugs:
        - kde-frameworks-5-plug
        - home
        - x11
        - opengl
        - network
        - network-bind
        - unity7
        - pulseaudio
        - desktop
        - desktop-legacy
        common-id: net.rpdev.OpenTodoList
        desktop: "usr/share/applications/net.rpdev.OpenTodoList.desktop"
plugs:
    kde-frameworks-5-plug:
        interface: content # type
        content: kde-frameworks-5-core18-all # the slot
        default-provider: kde-frameworks-5-core18 # the snap which provides the slot (ideally)
        target: kf5 # the target path where we want the content snap mounted into our scope
parts:
    opentodolist:
        build-snaps:
        - kde-frameworks-5-core18-sdk/stable
        build-packages:
        - build-essential
        - libgl1-mesa-dev
        after:
        - kde-frameworks-5-env
        plugin: qmake
        source: .
        options:
        - "INSTALL_PREFIX=/usr"
        - "CONFIG+=release"
        parse-info: [usr/share/appdata/net.rpdev.OpenTodoList.appdata.xml]
    kde-frameworks-5-env:
        plugin: dump
        source: https://github.com/apachelogger/kf5-snap-env.git
