name: opentodolist
version: 3.15.0
confinement: strict
grade: stable
base: core18
adopt-info: opentodolist # part to adopt appstream data from (first in parse list)
apps:
    opentodolist:
        command: kf5-launch OpenTodoList
        plugs:
        - kde-frameworks-5-plug
        - home
        - x11
        - opengl
        - network
        - network-bind
        - unity7
        - pulseaudio
        - desktop
        - desktop-legacy
        common-id: net.rpdev.OpenTodoList
        desktop: "usr/share/applications/net.rpdev.OpenTodoList.desktop"
plugs:
    kde-frameworks-5-plug:
        content: kde-frameworks-5-all
        interface: content
        default-provider: kde-frameworks-5
        target: kf5
parts:
    opentodolist:
        build-snaps:
        - kde-frameworks-5-core18-sdk/stable
        build-packages:
        - build-essential
        after:
        - kde-frameworks-5-env
        plugin: cmake
        source: .
        configflags:
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_BUILD_TYPE=Release"
        parse-info: [usr/share/appdata/net.rpdev.OpenTodoList.appdata.xml]
    kde-frameworks-5-env:
        plugin: dump
        source: https://github.com/apachelogger/kf5-snap-env.git
